2022-01-03 13:22:02,109 ERROR: Exception on /login [GET] [in C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Simone Dalle Vedove\Desktop\Varie\Progetti Flask\info_copping - official\app\routes.py", line 63, in login
    form = LoginForm()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\csrf\core.py", line 44, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 147, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 36, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2022-01-03 13:22:02,789 ERROR: Exception on /login [GET] [in C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Simone Dalle Vedove\Desktop\Varie\Progetti Flask\info_copping - official\app\routes.py", line 63, in login
    form = LoginForm()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\csrf\core.py", line 44, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 147, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 36, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2022-01-03 13:22:02,977 ERROR: Exception on /login [GET] [in C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Simone Dalle Vedove\Desktop\Varie\Progetti Flask\info_copping - official\app\routes.py", line 63, in login
    form = LoginForm()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\wtforms\csrf\core.py", line 44, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 147, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 36, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_wtf\csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2022-01-03 13:22:05,430 ERROR: Exception on / [GET] [in C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\login_manager.py", line 165, in unauthorized
    flash(self.login_message, category=self.login_message_category)
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 391, in flash
    session["_flashes"] = flashes
  File "C:\Users\Simone Dalle Vedove\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2022-01-03 13:22:57,483 INFO: Info Copping startup [in C:\Users\Simone Dalle Vedove\Desktop\Varie\Progetti Flask\info_copping - official\app\__init__.py:47]
2022-01-03 13:24:44,010 INFO: Info Copping startup [in C:\Users\Simone Dalle Vedove\Desktop\Varie\Progetti Flask\info_copping - official\app\__init__.py:47]
